version: '3'

services:
  database-nest:
    image: 'postgres'
    environment:
      POSTGRES_USER: unicorn_user
      POSTGRES_PASSWORD: magical_password
      POSTGRES_DB: nest_react_database
    ports:
      - '5434:5432'
    volumes:
      - database-data-nest:/var/lib/postgresql/data/
volumes:
  database-data-nest:
